import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      // Faqat unused qoidalarni yoqish
      "no-unused-vars": "warn",
      "@typescript-eslint/no-unused-vars": "warn",
      
      // Barcha boshqa qoidalarni o'chirish
      "@typescript-eslint/no-floating-promises": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-return": "off",
      "@typescript-eslint/no-unnecessary-type-assertion": "off",
      "@typescript-eslint/explicit-module-boundary-types": "off",
      "react-hooks/exhaustive-deps": "off",
      "react/jsx-key": "off",
      "react/no-unescaped-entities": "off",
      "no-console": "off",
      "no-debugger": "off",
      "no-undef": "off",
      "no-empty": "off",
      "no-empty-function": "off",
      "no-redeclare": "off",
      "no-extra-semi": "off",
      "no-unreachable": "off",
      "no-constant-condition": "off",
      "no-case-declarations": "off",
      "no-fallthrough": "off",
      "no-prototype-builtins": "off",
      "no-useless-escape": "off",
      "no-var": "off",
      "prefer-const": "off",
      "prefer-rest-params": "off",
      "prefer-spread": "off",
      "prefer-promise-reject-errors": "off",
      "require-await": "off",
      "valid-typeof": "off",
      "no-mixed-spaces-and-tabs": "off",
      "no-irregular-whitespace": "off",
      "no-unexpected-multiline": "off",
      "no-extra-boolean-cast": "off",
      "no-async-promise-executor": "off",
      "no-misleading-character-class": "off",
      "no-useless-catch": "off",
      "no-shadow": "off",
      "no-undef-init": "off",
      "no-unused-expressions": "off",
      "no-unused-labels": "off",
      "no-unsafe-finally": "off",
      "no-unsafe-negation": "off",
      "no-implied-eval": "off",
      "no-throw-literal": "off",
      "no-with": "off",
      "no-alert": "off",
      "no-eval": "off",
      "no-global-assign": "off",
      "no-iterator": "off",
      "no-proto": "off",
      "no-script-url": "off",
      "no-self-assign": "off",
      "no-self-compare": "off",
      "no-sequences": "off",
      "no-unmodified-loop-condition": "off",
      "no-unused-private-class-members": "off",
      "no-use-before-define": "off",
      "no-restricted-globals": "off",
      "no-restricted-properties": "off",
      "no-restricted-syntax": "off",
      "no-return-await": "off",
      "no-sync": "off",
      "no-await-in-loop": "off",
      "no-bitwise": "off",
      "no-caller": "off",
      "no-cond-assign": "off",
      "no-const-assign": "off",
      "no-control-regex": "off",
      "no-delete-var": "off",
      "no-dupe-args": "off",
      "no-dupe-else-if": "off",
      "no-dupe-keys": "off",
      "no-duplicate-case": "off",
      "no-empty-character-class": "off",
      "no-ex-assign": "off",
      "no-extra-bind": "off",
      "no-extra-label": "off",
      "no-func-assign": "off",
      "no-import-assign": "off",
      "no-inner-declarations": "off",
      "no-invalid-regexp": "off",
      "no-new-symbol": "off",
      "no-obj-calls": "off",
      "no-octal": "off",
      "no-regex-spaces": "off",
      "no-setter-return": "off",
      "no-sparse-arrays": "off",
      "no-this-before-super": "off",
      "no-unreachable-loop": "off",
      "no-unsafe-optional-chaining": "off",
      "no-unused-imports": "off",
      "no-useless-backreference": "off",
      "no-useless-rename": "off",
      "no-void": "off",
      "no-warning-comments": "off",
      "require-yield": "off",
      "use-isnan": "off",
      "constructor-super": "off",
      "for-direction": "off",
      "getter-return": "off",
      "grouped-accessor-pairs": "off",
      "guard-for-in": "off",
      "new-cap": "off",
      "no-array-constructor": "off",
      "no-class-assign": "off",
      "no-compare-neg-zero": "off",
      "no-cond-assign": "off",
      "no-const-assign": "off",
      "no-constant-binary-expression": "off",
      "no-constructor-return": "off",
      "no-dupe-class-members": "off",
      "no-duplicate-imports": "off",
      "no-empty-pattern": "off",
      "no-new-native-nonconstructor": "off",
      "no-return-assign": "off",
      "no-super": "off",
      "no-template-curly-in-string": "off",
      "no-this-before-super": "off",
      "no-undef": "off",
      "no-unused-private-class-members": "off",
      "no-useless-computed-key": "off",
      "no-useless-constructor": "off",
      "no-useless-escape": "off",
      "no-useless-rename": "off",
      "no-var": "off",
      "object-shorthand": "off",
      "prefer-arrow-callback": "off",
      "prefer-const": "off",
      "prefer-destructuring": "off",
      "prefer-numeric-literals": "off",
      "prefer-object-spread": "off",
      "prefer-rest-params": "off",
      "prefer-spread": "off",
      "prefer-template": "off",
      "require-atomic-updates": "off",
      "require-await": "off",
      "require-yield": "off",
      "sort-imports": "off",
      "symbol-description": "off",
      "unicode-bom": "off",
      "use-isnan": "off",
      "valid-typeof": "off",
      "vars-on-top": "off",
      "yoda": "off",
    },
  },
];

export default eslintConfig;